#!/bin/bash
# Please change this if you do not work at Socialsquare :)
UPLOAD_URL="http://socialsquare.dk/lolcommits/"
# Setting some variables 
OUTPUT_DIR="/tmp/lolcommit"

if [ -c /dev/video1 ]; then
	VIDEO_DEVICE="/dev/video1"
else
	VIDEO_DEVICE="/dev/video0"
fi

AUTHOR=$(git log -1 HEAD --format=%an)
MESSAGE=$(git log -1 HEAD --format=%s)
HASH=$(git log -1 HEAD --format=%H)
IMAGE_SIZE="400x300"
CAPTURED_TIME="1s"

(
	mkdir $OUTPUT_DIR
	# Waiting
	sleep 1
	# Using avconv
	avconv -f video4linux2 -i $VIDEO_DEVICE -vsync 1 -r 15 -an -y -s $IMAGE_SIZE -t $CAPTURED_TIME $OUTPUT_DIR/frame-%04d.jpg

	# Concatinate all these images into commandline arguments for curl.
	file_args=()
	for file in $OUTPUT_DIR/*
	do
	    file_args+="-F \"image[]=@$file\" "
	done;
	# Call cURL with images, message, author and hash.
	echo $file_args | xargs curl -g -X POST \
	  -F "message=$MESSAGE" \
	  -F "author=$AUTHOR" \
	  -F "hash=$HASH" \
	  $UPLOAD_URL

	# Clean up
	rm -rf $OUTPUT_DIR
) > /dev/null 2>&1 & # Send to the background - without outputting stdout
